### ISSUE TITLE
o'zgaruvchilarni nomlash

### ISSUE THREAD

**Issue by ozbeg** [UmarAbdurazzoq/shoping-list#1]
<img width="474" alt="Screen Shot 2020-11-10 at 11 32 42" src="https://user-images.githubusercontent.com/68459737/98636329-74418300-2348-11eb-930b-ad2df05c4e68.png">
umumi nomlardan foydalanmagan yaxshiroq 👍

**Comment by UmarAbdurazzoq** [comment]
ok tuzatamiz

**Comment by UmarAbdurazzoq** [comment]
fixed this issue thank you :)
